#importonce
#import "commodore.inc"

//----------------------------------------------------------
//
//	HW specific
//
//----------------------------------------------------------

.const	SCREENADDR	=	$0400
.const	SCREENW		=	40
.const	SCREENH		=	25

//----------------------------------------------------------
//
//	Game specific
//
//----------------------------------------------------------

.const	SCENEOFFSET	=	SCREENW + 11
.const	SCENEW		=	29	// Size of displayed scene
.const	SCENEH		=	24
