#importonce
#import "commodore.inc"

//----------------------------------------------------------
//
//	HW specific
//
//----------------------------------------------------------

.const	SCREENADDR	=	$0400
.const	SCREENW		=	40
.const	SCREENH		=	25

//----------------------------------------------------------
//
//	Game specific
//
//----------------------------------------------------------

.const	DUNGEONOFFSET	=	SCREENW + 11
.const	DUNGEONW	=	29
.const	DUNGEONH	=	24
